### ISSUE TITLE
卡片回调不成功

### ISSUE THREAD

**Issue by Yaocool** [open-dingtalk/dingtalk-stream-sdk-python#19]
审批卡片点击按钮未发起回调，按钮 actionType 已设为 request，请问这是怎么回事呢 @chzealot

**Comment by chzealot** [comment]
帮忙发一下审批片的相关代码，查看是否审批卡片构建有问题

**Comment by ginping** [comment]
> 审批卡片点击按钮未发起回调，按钮 actionType 已设为 request，请问这是怎么回事呢 @chzealot

可以贴一下代码，并确认发起审批卡片的机器人应用和运行 Stream 服务传入的 client_id 是同一个应用。
