### ISSUE TITLE
找不到权限点Card.Streaming.Write

### ISSUE THREAD

**Issue by Iceberry-qdd** [open-dingtalk/dingtalk-stream-sdk-python#20]
您好，我目前在尝试使用[`AIMarkdownCardInstance`](https://github.com/open-dingtalk/dingtalk-stream-sdk-python/blob/main/dingtalk_stream/card_instance.py#L151)类下的[`ai_streaming`](https://github.com/open-dingtalk/dingtalk-stream-sdk-python/blob/2be1f94ae31ab74aea38b60f26dc9b41556b312c/dingtalk_stream/card_instance.py#L227-L251)进行流式更新卡片内容时，程序会报403异常，根据报错信息，是缺少权限点`Card.Streaming.Write`，但是在官网找不到该权限点。

具体是在调用如下位置时报错：
https://github.com/open-dingtalk/dingtalk-stream-sdk-python/blob/2be1f94ae31ab74aea38b60f26dc9b41556b312c/dingtalk_stream/card_replier.py#L281-L290

调用后响应体内容为：
```json
{
    "code": "Forbidden.AccessDenied.AccessTokenPermissionDenied",
    "requestid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "message": "...https://open.dingtalk.com/document/orgapp-server/add-api-permission",
    "accessdenieddetail": {
        "requiredScopes": ["Card.Streaming.Write"]
    }
}
```

在官网找不到该权限点：
![image](https://github.com/open-dingtalk/dingtalk-stream-sdk-python/assets/59782644/fd433c95-62d7-421f-8417-c6065596234c)

**Comment by chzealot** [comment]
抱歉该接口还在内测中，仅在 SDK 代码中透出，文档和权限点均未对外开放，可以先参考其他已经全量发布的能力。
