### ISSUE TITLE
update_card 特定内容永远调用失败

### ISSUE THREAD

**Issue by Yaocool** [open-dingtalk/dingtalk-stream-sdk-python#21]

**Comment by chzealot** [comment]
看描述像是参数错误，为了高效解决问题，请提供以下信息协助问题诊断：

* 应用 ClientID （对应 AppKey 或者 SuiteKey）
* 调用接口的日期和时间
* 调用的接口URL，或者对应的开放平台文档链接，或者调用 SDK 的相关代码 （推荐提供接口 URL ，或者接口对应的文档 URL）
* 调用接口时候传入的参数，注意对敏感信息脱敏。脱敏时候尽量保留 json 数据的格式信息
* 钉钉开放平台返回的错误信息
* 接口的 RequestID

**Comment by Yaocool** [comment]
> 看描述像是参数错误，为了高效解决问题，请提供以下信息协助问题诊断：
> 
> * 应用 ClientID （对应 AppKey 或者 SuiteKey）
> * 调用接口的日期和时间
> * 调用的接口URL，或者对应的开放平台文档链接，或者调用 SDK 的相关代码 （推荐提供接口 URL ，或者接口对应的文档 URL）
> * 调用接口时候传入的参数，注意对敏感信息脱敏。脱敏时候尽量保留 json 数据的格式信息
> * 钉钉开放平台返回的错误信息
> * 接口的 RequestID

ClientID: dingmun2pxvr65biat6i
日期/时间：2023年10月18日，具体时间点暂无
调用的接口： URL:https://api.dingtalk.com/v1.0/im/robots/interactiveCards
调用接口传参：
`json
{
	"card_biz_id": "daddecc5955a02c2cc83178a6af906773e0e412f050bd2f9cb3542b40004150e",
	"card-data": "{ 'config': { 'autoLayout': True, 'enableForward': True }, 'header': { 'title': { 'type': 'text', 'text': 'Bot' } }, 'contents': [ { 'type': 'markdown', 'text': '**Q: *报销有啥要注意的吗?***  <br>  <br>  **A**: 在xxx公司，报销需要注意以下几点：\n\n1. 真实性：所有员工必须做到廉洁自律，如实报销，如经查出有伪造凭证、报销不实等行为，将按照公司有关规定进行处理。\n\n2. 及时性：员工的日常人民币报销通过银行转账方式进行，为保证报销的效率，员工应及时将银行卡号提交人事部。\n\n3. 个人原因产生的相关费用不予报销：包括个人财产损失、差旅借款丢失、由于个人不良行为承担产生的责任而产生的罚款、过度的及不符合道德规范的业务招待支出、其他用于个人消费的支出等。\n\n4. 费用员工独立报销：一般情况下，员工只能报销自己发生的费用，只有当所要报销的费用不宜按人员划分开来报时，才可由其中最高级别的员工报销，但须在报销单上列出其他员工的姓名。\n\n5. 不得分拆报销：报销时禁止分项、分段拆单，即对同一目的、相同时间段内发生的费用，需填写一份报销单据，按合计后的金额进行费用审批，不得分开报销。\n\n6. 统一格式：审批完成的报销单必须用 A4 纸打印，连同全部发票及相关附件一同提交财务部。\n\n7. 报销期限：报销的票据需在出具后的一个月内报销，票据日期与报销事项发生的日期应该一致，从发票开具之日算起，超过一个月的发票，公司有权延迟或者不予报销。\n\n8. 报销发放时间：每月的 20 日为固定报销发放日，如遇周末和节假日顺延至第一个工作日。\n\n以上就是报销需要注意的一些事项，希望对你有所帮助。\n\n>  这是AI作答。本次知识来源：\n1.[费用报销管理制度---报销原则>真实性,及时性---xxxx](https://alidocs.dingtalk.com/i/nodes/xxxxxxx?utm_scene=team_space)\n2.[费用报销管理制度---其他相关规定---xxx](https://alidocs.dingtalk.com/i/nodes/xxxxxxxx?utm_scene=team_space)\n3.[费用报销管理制度---报销涉及的相关时间>员工报销期限及发放时间---xxx](https://alidocs.dingtalk.com/i/nodes/xxxxxxxxxxx?utm_scene=team_space)', } ] }"
}
`
返回的错误信息：
update card failed, error=400 Client Error: Bad Request for url: https://api.dingtalk.com/v1.0/im/robots/interactiveCards, response={"code":"InvalidcardData","requestid":"4F85FA6C-63AB-7E19-B88A-6C6E31ED0CCE","message":"Specified parameter cardData is not valid."}

requestID: 4F85FA6C-63AB-7E19-B88A-6C6E31ED0CCE"

**Comment by Yaocool** [comment]
> 看描述像是参数错误，为了高效解决问题，请提供以下信息协助问题诊断：
> 
> * 应用 ClientID （对应 AppKey 或者 SuiteKey）
> * 调用接口的日期和时间
> * 调用的接口URL，或者对应的开放平台文档链接，或者调用 SDK 的相关代码 （推荐提供接口 URL ，或者接口对应的文档 URL）
> * 调用接口时候传入的参数，注意对敏感信息脱敏。脱敏时候尽量保留 json 数据的格式信息
> * 钉钉开放平台返回的错误信息
> * 接口的 RequestID

请问这个问题是否有进展了呢 @chzealot
