### ISSUE TITLE
间隔20个小时左右再调用会报错 

### ISSUE THREAD

**Issue by Genie0s** [open-dingtalk/dingtalk-stream-sdk-python#22]
received disconnect topic=disconnect, message={'specVersion': '1.0', 'type': 'SYSTEM', 'headers': {'contentType': 'application/json', 'messageId': 'c0a815dd1698551133918195d43', 'time': '1698551133918', 'topic': 'disconnect'}, 'data': '{"reason":"persistent connection is timeout"}'}
后台是这个问题

**Comment by lijiapengsa** [comment]
Me too

**Comment by lijiapengsa** [comment]
It's OK now, No such problem has arisen again

**Comment by chzealot** [comment]
该问题已经修复，可以继续观察是否还有问题。
