### ISSUE TITLE
请教下如何通过代理访问呢？

### ISSUE THREAD

**Issue by robinpeng200** [open-dingtalk/dingtalk-stream-sdk-python#28]
请教下如何通过代理访问呢？ 公司服务器不能直接访问外网，需要通过一台能连外网的服务器访问，这台服务器上部署有squid代理，这种情况下，如何设置 dingtalk-stream-sdk-python 的代理配置呢？

**Comment by chzealot** [comment]
暂时不支持通过代理访问，可以采用 HTTP 方式接收消息。
