### ISSUE TITLE
卡片回调接收不到

### ISSUE THREAD

**Issue by FrankWangZY** [open-dingtalk/dingtalk-stream-sdk-python#29]
试了node 和 python的，卡片回调无论是普通卡片还是高级卡片使用stream 都接收不到，普通消息是可以接收的，请帮忙看下原因
![image](https://github.com/open-dingtalk/dingtalk-stream-sdk-python/assets/28087610/e78b9e6c-c277-4255-a8ca-f6be7f9f2185)

**Comment by chzealot** [comment]
调用发送卡片消息的接口时候，需要指定回调相关参数

**Comment by ginping** [comment]
> 片消息的接口时候，需要指定回调相关

建议贴一下你的 main 函数代码，client 要注册 TOPIC 为 dingtalk_stream.CallbackHandler.TOPIC_CARD_CALLBACK 的回调函数。
