### ISSUE TITLE
是否支持回复消息时，也能有类似 chatgpt 的效果，回复的内容能动态新增。

### ISSUE THREAD

**Issue by XFOpenAPI** [open-dingtalk/dingtalk-stream-sdk-python#32]
我设置的机器人所对应的后台是一个 AI 助理，希望在钉钉中回复消息时，也能有 chatgpt 回复时的效果，请问是否支持？

**Comment by chzealot** [comment]
可以参考这个文档采用打字机模式：https://opensource.dingtalk.com/developerpedia/docs/explore/tutorials/stream/bot/go/send-streaming-card

**Comment by XFOpenAPI** [comment]
已经验证成功，谢谢。
