### ISSUE TITLE
请问下建立websocket连接后，是否有方法能够主动关闭连接

### ISSUE THREAD

**Issue by Kevin9703** [open-dingtalk/dingtalk-stream-sdk-python#40]

**Comment by chzealot** [comment]
这个需求的目的是什么？

**Comment by Alex-wwei** [comment]
[这个问题没解决吗？我们用langbot项目](https://github.com/langbot-app/LangBot) ，项目里用该框架跟钉钉对接，其中把实例丢给异步协程，导致进程无法管理，关不掉（即websocket关不掉）
