### ISSUE TITLE
命名冲突导致同步方法意外调用异步方法

### ISSUE THREAD

**Issue by cmgzn** [open-dingtalk/dingtalk-stream-sdk-python#50]
https://github.com/open-dingtalk/dingtalk-stream-sdk-python/blob/262f2bfeea61be20d689964eae25f0223061344d/dingtalk_stream/card_replier.py#L689

## 描述
当前代码库中有两个名为 `finish` 的方法，其中一个为异步方法 (`async def finish(...)`)，另一个为同步方法 (`def finish(...)`）。由于命名冲突，当尝试调用同步方法时，实际上调用了异步方法，导致运行时警告 `coroutine '...was never awaited'`。

## 步骤重现
1. 调用同步方法 `self.finish(...)`
2. 观察到实际调用的是异步方法 `async def finish(...)`

## 影响
- 引发不必要的 `RuntimeWarning`
- 导致代码难以维护和调试

## 建议解决方案
建议重命名其中一个方法以消除命名冲突。例如：
- 将异步方法命名为 `async_definish(...)`
- 或者将同步方法命名为 `sync_finish(...)`

这样可以清晰地区分同步和异步方法，避免此类问题的发生。

谢谢！

**Comment by ginping** [comment]
感谢反馈，已将同名异步函数 finish 名称改为 async_finish
